build:
  environment:
    php:
      version: 7.0.6

checks:
  php: true

tests: false

filter:
  excluded_paths:
    - "app/*"
    - "bin/*"
    - "tests/*"
    - "var/*"
    - "src/AppBundle/Fixture/*"
    - "src/AppBundle/Command/Composer/*"
